# Generated by Django 5.0.4 on 2024-04-10 12:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_todo_user_delete_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='todo',
            unique_together={('user', 'body')},
        ),
    ]
